---
title: "Código de Análisis de Datos"
author: "Cristóbal Ortiz"
output: html_document
---

```{r setup-markdown,include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = TRUE)
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
options(knitr.kable.NA = '')
```

```{r load-library, include=FALSE}
library(tidyverse)
library(lme4)
library(texreg)
library(vtable)
library(psych)
library(sjPlot)
library(cowplot)

library(lavaan)
library(lavaanPlot)
library(semPlot)
library(foreign)
library(sjmisc)
library(knitr)
library(semTable)
library(semptools)
#devtools::install_github("dr-JT/semoutput") #de aquí sale sem_paths
library(semoutput)
library(stargazer)
```

```{r load-dataset-proc, include=FALSE}
getwd()
rm(list=ls())
load("../1_input/data/procesada/elsoc_ams.RData")
load("../3_output/modelos/sem_models.RData")
#View(elsoc_sub)

elsoc_sub <- elsoc_ams %>% 
  dplyr::select(idencuesta, cod_zona, 
                apbi, soci, 
                segui, repbi, sacci, 
                edadi, educi, essui, time, 
                hete, segr, hi_theil, ismtpn, gse_prom, gse_dom, ent_mean, ent_wgt, ent_segr, ave_jane) %>% 
  drop_na()

elsoc_sub_gse <- elsoc_ams %>% 
  dplyr::select(idencuesta, cod_zona, 
                apbi, soci, 
                segui, repbi, sacci, 
                edadi, educi, educ, essui, time, 
                hete, segr, hi_theil, ismtpn, gse_prom, gse_dom, ent_mean, ent_wgt, ent_segr, ave_jane) %>% 
  drop_na()
```

# Modelos de ecuaciones estructurales (análisis de senderos multinivel)

## Mediación Multinivel: upper-level mediation (2-1-1)

```{r msem-apbi, warning=FALSE}
msem_apbi <- '
level: 1
      # Modelo estructural nivel 1
      apbi ~ b1*segui + b2*repbi + b3*sacci + b4*edadi + b5*educi + b6*essui + b7*time

      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci
      
level: 2
      # Modelo estructural nivel 2
      apbi ~ b1*segui + b2*repbi + b3*sacci + c1*ent_segr + c2*ave_jane
      segui ~ a1*ent_segr
      repbi ~ a2*ent_segr
      repbi ~ a3*ave_jane
      sacci ~ a4*ave_jane
      
      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci

      # Efecto indirecto 
      ind_segr_segui_apbi := a1*b1
      ind_segr_repbi_apbi := a2*b2
      ind_jane_repbi_apbi := a3*b2
      ind_jane_sacci_apbi := a4*b3

      # Efecto total 
      tot_segr_segui_apbi := c1 + (a1*b1)
      tot_segr_repbi_apbi := c1 + (a2*b2)
      tot_jane_repbi_apbi := c2 + (a3*b2)
      tot_jane_sacci_apbi := c2 + (a4*b3)
'

#fit_msem_apbi <- sem(msem_apbi, data = elsoc_sub, cluster = "cod_zona")
#fit_msem <- sem(msem_apbi, data = elsoc_sub, cluster = "cod_zona", verbose = TRUE, optim.method = "em", em.iter.max = 20000,  em.fx.tol = 1e-08, em.dx.tol = 1e-04)

summary(fit_msem_apbi, fit.measures = T)
```

```{r msem-table-apbi}
sem_table_apbi <- sem_paths(fit_msem_apbi, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
sem_table_apbi %>% cat(., file = "../3_output/tablas/sem_table_apbi.doc")
sem_table_apbi
```

```{r fit-measure-apbi}
options(digits = 3)

ajust_apbi <- fitMeasures(fit_msem_apbi, c("chisq", "cfi","rmsea","srmr")) %>% 
  as.data.frame() %>% 
  rownames_to_column("measure")

writexl::write_xlsx(ajust_apbi, path ="../3_output/tablas/ajust_table_apbi.xlsx")

lavInspect(fit_msem_apbi, "icc")
lavInspect(fit_msem_apbi, "r2")
```

```{r msem-soci, warning=FALSE}
msem_soci <- '
level: 1
      # Modelo estructural nivel 1
      soci ~ b1*segui + b2*repbi + b3*sacci + b4*edadi + b5*educi + b6*essui + b7*time

      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci
      
level: 2
      # Modelo estructural nivel 2
      soci ~ b1*segui + b2*repbi + b3*sacci + c1*ent_segr + c2*ave_jane
      segui ~ a1*ent_segr
      repbi ~ a2*ent_segr
      repbi ~ a3*ave_jane
      sacci ~ a4*ave_jane
      
      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci

      # Efecto indirecto 
      ind_segr_segui_soci := a1*b1
      ind_segr_repbi_soci := a2*b2
      ind_jane_repbi_soci := a3*b2
      ind_jane_sacci_soci := a4*b3
      
      # Efecto total 
      tot_segr_segui_soci := c1 + (a1*b1)
      tot_segr_repbi_soci := c1 + (a2*b2)
      tot_jane_repbi_soci := c2 + (a3*b2)
      tot_jane_sacci_soci := c2 + (a4*b3)
'

#fit_msem_soci <- sem(msem_soci, data = elsoc_sub, cluster = "cod_zona")
summary(fit_msem_soci, fit.measures = T)
```

```{r msem-table-soci}
sem_table_soci <- sem_paths(fit_msem_soci, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
sem_table_soci %>% cat(., file = "../3_output/tablas/sem_table_soci.doc")
sem_table_soci
```

```{r fit-measure-soci}
ajust_soci <- fitMeasures(fit_msem_soci, c("chisq", "cfi","rmsea","srmr")) %>% 
  as.data.frame() %>% 
  rownames_to_column("measure")

writexl::write_xlsx(ajust_soci, path ="../3_output/tablas/ajust_table_soci.xlsx")

lavInspect(fit_msem_soci, "icc")
```

```{r coef-table}
coef_apbi <-
  broom::tidy(fit_msem_apbi, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>% 
  filter(label %in% c("b1", "b2", "b3", "c1", "c2", "ind_segr_segui_apbi", "ind_segr_repbi_apbi", "ind_jane_repbi_apbi", "ind_jane_sacci_apbi")) %>% 
  data_frame(var = c(rep("Pertenencia"))) %>% 
  dplyr::select(var, term, estimate, conf.low, conf.high)

# soci
coef_soci <-
  broom::tidy(fit_msem_soci, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>%    
  filter(label %in% c("b1", "b2", "b3", "c1", "c2", "ind_segr_segui_soci", "ind_segr_repbi_soci", "ind_jane_repbi_soci", "ind_jane_sacci_soci")) %>% 
  data_frame(var = c(rep("Sociabilidad"))) %>% 
  dplyr::select(var, term, estimate, conf.low, conf.high)

coef_msem <- rbind(coef_apbi, coef_soci)
```

```{r coef-graph, warning=FALSE}
coef_msem <- coef_msem %>% 
  mutate(term = recode(term, 
                       "apbi ~ segui" = "Seguridad",
                       "soci ~ segui" = "Seguridad",
                       "apbi ~ repbi" = "Reputación",
                       "soci ~ repbi" = "Reputación",
                       "apbi ~ sacci" = "Satisfacción",
                       "soci ~ sacci" = "Satisfacción",
                       "apbi ~ ent_segr" = "Segregación",
                       "soci ~ ent_segr" = "Segregación",
                       "apbi ~ ave_jane" = "Vitalidad",
                       "soci ~ ave_jane" = "Vitalidad",
                       "ind_segr_segui_apbi := a1*b1" = "Segregación ~\nSeguridad",
                       "ind_segr_segui_soci := a1*b1" = "Segregación ~\nSeguridad",
                       "ind_segr_repbi_apbi := a2*b2" = "Segregación ~\nReputación",
                       "ind_segr_repbi_soci := a2*b2" = "Segregación ~\nReputación",
                       "ind_jane_repbi_apbi := a3*b2" = "Vitalidad ~\nReputación",
                       "ind_jane_repbi_soci := a3*b2" = "Vitalidad ~\nReputación",
                       "ind_jane_sacci_apbi := a4*b3" = "Vitalidad ~\nSatisfacción",
                       "ind_jane_sacci_soci := a4*b3" = "Vitalidad ~\nSatisfacción"))

coef_plot <- coef_msem %>% 
  ggplot(aes(x = factor(term, levels = c('Seguridad', 'Reputación', 'Satisfacción', "Segregación", "Vitalidad",
                                         'Segregación ~\nSeguridad', 'Segregación ~\nReputación',
                                         'Vitalidad ~\nReputación', 'Vitalidad ~\nSatisfacción')), 
           y = estimate)) +
  geom_hline(yintercept = 0, color = 'red') +
  geom_point(position = position_dodge(width = -0.6), size = 3) +
  geom_linerange(aes(ymin = conf.low, ymax = conf.high),
                 position = position_dodge(width = -0.6), 
                 size = .8) +
  coord_flip() +
  facet_wrap(.~ var) +
  theme(axis.text = element_text(size =  10),
        axis.title = element_text(size = 10, face = "bold")) +
  labs(title = "",
       x = "",
       y = "Coeficientes estandarizados") +
  scale_x_discrete(limits = rev) 

coef_plot

ggsave(coef_plot,filename = "../3_output/graficos/coef_plot.png", width = 10, height = 7)
```

## Mediación multinivel por grupos socioeconómicos (msem 2-1-1)


```{r subset-class}
quantile(elsoc_sub$educi)
#  0%  25%  50%  75% 100% 
#  1    4    5    7   10 

#subset para 0%-25%
elsoc_low <- elsoc_sub %>% 
  filter(educi <= quantile(elsoc_sub$educi)[2]) %>% 
  dplyr::select(-educi)

#subset para 25%-50%
elsoc_middle_low <- elsoc_sub %>% 
  filter((educi >= quantile (elsoc_sub$educi)[2] &
            educi <= quantile(elsoc_sub$educi)[3])) %>% 
  dplyr::select(-educi)

#subset para 50%-75%
elsoc_middle_high <- elsoc_sub %>% 
  filter((educi > quantile (elsoc_sub$educi)[3] &
            educi <= quantile(elsoc_sub$educi)[4])) %>% 
  dplyr::select(-educi)

#subset para 75%-100%
elsoc_high <- elsoc_sub %>% 
  filter(educi > quantile (elsoc_sub$educi)[4]) %>% 
  dplyr::select(-educi)
```


```{r sem-apbi-soci}
sem_apbi <- '
      # Modelo estructural nivel 1
      apbi ~ b1*segui + b2*repbi + b3*sacci + b4*edadi + b5*time

      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci
      edadi ~~ time
      '

sem_soci <- '
      # Modelo estructural nivel 1
      soci ~ b1*segui + b2*repbi + b3*sacci + b4*edadi + b5*time

      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci
      edadi ~~ time
      '
```

```{r msem-apbi-soci-2, warning=FALSE}
msem_apbi2 <- '
level: 1
      # Modelo estructural nivel 1
      apbi ~ b1*segui + b2*repbi + b3*sacci + b4*edadi + b6*essui + b7*time

      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci
      
level: 2
      # Modelo estructural nivel 2
      apbi ~ b1*segui + b2*repbi + b3*sacci + c1*ent_segr + c2*ave_jane
      segui ~ a1*ent_segr
      repbi ~ a2*ent_segr
      repbi ~ a3*ave_jane
      sacci ~ a4*ave_jane
      
      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci

      # Efecto indirecto 
      ind_segr_segui_apbi := a1*b1
      ind_segr_repbi_apbi := a2*b2
      ind_jane_repbi_apbi := a3*b2
      ind_jane_sacci_apbi := a4*b3

      # Efecto total 
      tot_segr_segui_apbi := c1 + (a1*b1)
      tot_segr_repbi_apbi := c1 + (a2*b2)
      tot_jane_repbi_apbi := c2 + (a3*b2)
      tot_jane_sacci_apbi := c2 + (a4*b3)
'

#fit_msem_apbi <- sem(msem_apbi2, data = elsoc_sub, cluster = "cod_zona")
#summary(fit_msem_apbi, fit.measures = T)

msem_soci2 <- '
level: 1
      # Modelo estructural nivel 1
      soci ~ b1*segui + b2*repbi + b3*sacci + b4*edadi + b6*essui + b7*time

      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci
      
level: 2
      # Modelo estructural nivel 2
      soci ~ b1*segui + b2*repbi + b3*sacci + c1*ent_segr + c2*ave_jane
      segui ~ a1*ent_segr
      repbi ~ a2*ent_segr
      repbi ~ a3*ave_jane
      sacci ~ a4*ave_jane
      
      # Covarianzas
      segui ~~ repbi
      repbi ~~ sacci
      segui ~~ sacci

      # Efecto indirecto 
      ind_segr_segui_soci := a1*b1
      ind_segr_repbi_soci := a2*b2
      ind_jane_repbi_soci := a3*b2
      ind_jane_sacci_soci := a4*b3
      
      # Efecto total 
      tot_segr_segui_soci := c1 + (a1*b1)
      tot_segr_repbi_soci := c1 + (a2*b2)
      tot_jane_repbi_soci := c2 + (a3*b2)
      tot_jane_sacci_soci := c2 + (a4*b3)
'

#fit_msem_soci <- sem(msem_soci2, data = elsoc_sub, cluster = "cod_zona")
#summary(fit_msem_soci, fit.measures = T)
```

```{r msem-low, warning=FALSE}
#fit_sem_apbi_low <- sem(msem_apbi2, data = elsoc_low, cluster = "cod_zona",
#                        verbose = TRUE, optim.method = "em", em.iter.max = 20000,  em.fx.tol = 1e-08, em.dx.tol = 1e-04)
#fit_sem_soci_low <- sem(msem_soci2, data = elsoc_low, cluster = "cod_zona",
#                        verbose = TRUE, optim.method = "em", em.iter.max = 20000,  em.fx.tol = 1e-08, em.dx.tol = 1e-04)

summary(fit_sem_apbi_low, fit.measures = F, standardized = TRUE)
summary(fit_sem_soci_low, fit.measures = F, standardized = TRUE)

low_table_apbi <- sem_paths(fit_sem_apbi_low, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
low_table_apbi %>% cat(., file = "../3_output/tablas/gse_tables/low_table_apbi.doc")
low_ajust_apbi <- fitMeasures(fit_sem_apbi_low, c("chisq", "cfi","rmsea","srmr")) %>% as.data.frame() %>% rownames_to_column("measure")
writexl::write_xlsx(low_ajust_apbi, path ="../3_output/tablas/gse_tables/low_ajust_apbi.xlsx")

low_table_soci <- sem_paths(fit_sem_soci_low, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
low_table_soci %>% cat(., file = "../3_output/tablas/gse_tables/low_table_soci.doc")
low_ajust_soci <- fitMeasures(fit_sem_soci_low, c("chisq", "cfi","rmsea","srmr")) %>% as.data.frame() %>% rownames_to_column("measure")
writexl::write_xlsx(low_ajust_soci, path ="../3_output/tablas/gse_tables/low_ajust_soci.xlsx")

```

```{r msem-middle-low, warning=FALSE}
#fit_sem_apbi_midlow <- sem(msem_apbi2, data = elsoc_middle_low, cluster = "cod_zona")
#fit_sem_soci_midlow <- sem(msem_soci2, data = elsoc_middle_low, cluster = "cod_zona",
#                           verbose = TRUE, optim.method = "em", em.iter.max = 20000,  em.fx.tol = 1e-08, em.dx.tol = 1e-04)

summary(fit_sem_apbi_midlow, fit.measures = F, standardized = TRUE)
summary(fit_sem_soci_midlow, fit.measures = F, standardized = TRUE)

midlow_table_apbi <- sem_paths(fit_sem_apbi_midlow, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
midlow_table_apbi %>% cat(., file = "../3_output/tablas/gse_tables/midlow_table_apbi.doc")
midlow_ajust_apbi <- fitMeasures(fit_sem_apbi_midlow, c("chisq", "cfi","rmsea","srmr")) %>% as.data.frame() %>% rownames_to_column("measure")
writexl::write_xlsx(midlow_ajust_apbi, path ="../3_output/tablas/gse_tables/midlow_ajust_apbi.xlsx")

midlow_table_soci <- sem_paths(fit_sem_soci_midlow, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
midlow_table_soci %>% cat(., file = "../3_output/tablas/gse_tables/midlow_table_soci.doc")
midlow_ajust_soci <- fitMeasures(fit_sem_soci_midlow, c("chisq", "cfi","rmsea","srmr")) %>% as.data.frame() %>% rownames_to_column("measure")
writexl::write_xlsx(midlow_ajust_soci, path ="../3_output/tablas/gse_tables/midlow_ajust_soci.xlsx")
```

```{r msem-middle-high, warning=FALSE}
#fit_sem_apbi_midhigh <- sem(msem_apbi2, data = elsoc_middle_high, cluster = "cod_zona", 
#                            verbose = TRUE, optim.method = "em", em.iter.max = 20000,  em.fx.tol = 1e-08, em.dx.tol = 1e-04)
#fit_sem_soci_midhigh <- sem(msem_soci2, data = elsoc_middle_high, cluster = "cod_zona",
#                            verbose = TRUE, optim.method = "em", em.iter.max = 20000,  em.fx.tol = 1e-08, em.dx.tol = 1e-04)

summary(fit_sem_apbi_midhigh, fit.measures = F, standardized = TRUE) #dont end normally
summary(fit_sem_soci_midhigh, fit.measures = F, standardized = TRUE) #dont end normally

midhigh_table_apbi <- sem_paths(fit_sem_apbi_midhigh, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
midhigh_table_apbi %>% cat(., file = "../3_output/tablas/gse_tables/midhigh_table_apbi.doc")
midhigh_ajust_apbi <- fitMeasures(fit_sem_apbi_midhigh, c("chisq", "cfi","rmsea","srmr")) %>% as.data.frame() %>% rownames_to_column("measure")
writexl::write_xlsx(midhigh_ajust_apbi, path ="../3_output/tablas/gse_tables/midhigh_ajust_apbi.xlsx")

midhigh_table_soci <- sem_paths(fit_sem_soci_midhigh, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
midhigh_table_soci %>% cat(., file = "../3_output/tablas/gse_tables/midhigh_table_soci.doc")
midhigh_ajust_soci <- fitMeasures(fit_sem_soci_midhigh, c("chisq", "cfi","rmsea","srmr")) %>% as.data.frame() %>% rownames_to_column("measure")
writexl::write_xlsx(midhigh_ajust_soci, path ="../3_output/tablas/gse_tables/midhigh_ajust_soci.xlsx")
```

```{r msem-high, warning=FALSE}
#fit_sem_apbi_high <- sem(msem_apbi2, data = elsoc_high, cluster = "cod_zona",
#                         verbose = TRUE, optim.method = "em", em.iter.max = 20000,  em.fx.tol = 1e-08, em.dx.tol = 1e-04)
fit_sem_soci_high <- sem(msem_soci2, data = elsoc_high, cluster = "cod_zona",
                         verbose = TRUE, optim.method = "em", em.iter.max = 20000,  em.fx.tol = 1e-08, em.dx.tol = 1e-04)

summary(fit_sem_apbi_high, fit.measures = F, standardized = TRUE) #dont end normally
summary(fit_sem_soci_high, fit.measures = F, standardized = TRUE)

high_table_apbi <- sem_paths(fit_sem_apbi_high, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
high_table_apbi %>% cat(., file = "../3_output/tablas/gse_tables/high_table_apbi.doc")
high_ajust_apbi <- fitMeasures(fit_sem_apbi_high, c("chisq", "cfi","rmsea","srmr")) %>% as.data.frame() %>% rownames_to_column("measure")
writexl::write_xlsx(high_ajust_apbi, path ="../3_output/tablas/gse_tables/high_ajust_apbi.xlsx")

high_table_soci <- sem_paths(fit_sem_soci_high, standardized = TRUE, ci = "standardized", ci_level = 0.95, print = TRUE)
high_table_soci %>% cat(., file = "../3_output/tablas/gse_tables/high_table_soci.doc")
high_ajust_soci <- fitMeasures(fit_sem_soci_high, c("chisq", "cfi","rmsea","srmr")) %>% as.data.frame() %>% rownames_to_column("measure")
writexl::write_xlsx(high_ajust_soci, path ="../3_output/tablas/gse_tables/high_ajust_soci.xlsx")
```

```{r coef-df-gse, warning=FALSE}
#apbi
coef_apbi_low <-
  broom::tidy(fit_sem_apbi_low, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>% 
  filter(label %in% c("b1", "b2", "b3", "ind_segr_segui_apbi", "ind_segr_repbi_apbi", "ind_jane_repbi_apbi", "ind_jane_sacci_apbi")) %>% 
  data_frame(class = c(rep("Bajo"))) %>% 
  dplyr::select(class, term, estimate, conf.low, conf.high) 

coef_apbi_midlow <-
  broom::tidy(fit_sem_apbi_midlow, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>%    
  filter(label %in% c("b1", "b2", "b3", "ind_segr_segui_apbi", "ind_segr_repbi_apbi", "ind_jane_repbi_apbi", "ind_jane_sacci_apbi")) %>% 
  data_frame(class = c(rep("Medio Bajo"))) %>% 
  dplyr::select(class, term, estimate, conf.low, conf.high)

coef_apbi_midhigh <-
  broom::tidy(fit_sem_apbi_midhigh, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>%    
  filter(label %in% c("b1", "b2", "b3", "ind_segr_segui_apbi", "ind_segr_repbi_apbi", "ind_jane_repbi_apbi", "ind_jane_sacci_apbi")) %>% 
  data_frame(class = c(rep("Medio alto"))) %>% 
  dplyr::select(class, term, estimate, conf.low, conf.high)

coef_apbi_high <-
  broom::tidy(fit_sem_apbi_high, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>%    
  filter(label %in% c("b1", "b2", "b3", "ind_segr_segui_apbi", "ind_segr_repbi_apbi", "ind_jane_repbi_apbi", "ind_jane_sacci_apbi")) %>% 
  data_frame(class = c(rep("Alto"))) %>% 
  dplyr::select(class, term, estimate, conf.low, conf.high)

coef_apbi_class <- rbind(coef_apbi_low, coef_apbi_midlow, coef_apbi_midhigh, coef_apbi_high) %>% 
  data_frame(var = c(rep("Pertenencia")))

# soci
coef_soci_low <-
  broom::tidy(fit_sem_soci_low, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>%    
  filter(label %in% c("b1", "b2", "b3", "ind_segr_segui_soci", "ind_segr_repbi_soci", "ind_jane_repbi_soci", "ind_jane_sacci_soci")) %>% 
  data_frame(class = c(rep("Bajo"))) %>% 
  dplyr::select(class, term, estimate, conf.low, conf.high)

coef_soci_midlow <-
  broom::tidy(fit_sem_soci_midlow, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>%    
  filter(label %in% c("b1", "b2", "b3", "ind_segr_segui_soci", "ind_segr_repbi_soci", "ind_jane_repbi_soci", "ind_jane_sacci_soci")) %>% 
  data_frame(class = c(rep("Medio Bajo"))) %>% 
  dplyr::select(class, term, estimate, conf.low, conf.high)

coef_soci_midhigh <-
  broom::tidy(fit_sem_soci_midhigh, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>%   
  filter(label %in% c("b1", "b2", "b3", "ind_segr_segui_soci", "ind_segr_repbi_soci", "ind_jane_repbi_soci", "ind_jane_sacci_soci")) %>% 
  data_frame(class = c(rep("Medio alto"))) %>% 
  dplyr::select(class, term, estimate, conf.low, conf.high)

coef_soci_high <-
  broom::tidy(fit_sem_soci_high, conf.int = TRUE, conf.level = 0.95) %>%
  filter(!level == 1) %>%    
  filter(label %in% c("b1", "b2", "b3", "ind_segr_segui_soci", "ind_segr_repbi_soci", "ind_jane_repbi_soci", "ind_jane_sacci_soci")) %>% 
  data_frame(class = c(rep("Alto"))) %>% 
  dplyr::select(class, term, estimate, conf.low, conf.high)

coef_soci_class <- rbind(coef_soci_low, coef_soci_midlow, coef_soci_midhigh, coef_soci_high) %>% 
  data_frame(var = c(rep("Sociabilidad")))

coef_class <- rbind(coef_apbi_class, coef_soci_class)
```

```{r coef-graph-gse, warning=FALSE}
coef_class <- coef_class %>% 
  mutate(term = recode(coef_class$term, 
                       "apbi ~ segui" = "Seguridad",
                       "soci ~ segui" = "Seguridad",
                       "apbi ~ repbi" = "Reputación",
                       "soci ~ repbi" = "Reputación",
                       "apbi ~ sacci" = "Satisfacción",
                       "soci ~ sacci" = "Satisfacción",
                       "ind_segr_segui_apbi := a1*b1" = "Segregación ~\nSeguridad",
                       "ind_segr_segui_soci := a1*b1" = "Segregación ~\nSeguridad",
                       "ind_segr_repbi_apbi := a2*b2" = "Segregación ~\nReputación",
                       "ind_segr_repbi_soci := a2*b2" = "Segregación ~\nReputación",
                       "ind_jane_repbi_apbi := a3*b2" = "Vitalidad ~\nReputación",
                       "ind_jane_repbi_soci := a3*b2" = "Vitalidad ~\nReputación",
                       "ind_jane_sacci_apbi := a4*b3" = "Vitalidad ~\nSatisfacción",
                       "ind_jane_sacci_soci := a4*b3" = "Vitalidad ~\nSatisfacción"))

coef_plot_gse <- coef_class %>% 
  ggplot(aes(x = factor(term, levels = c('Seguridad', 'Reputación', 'Satisfacción', 
                                         'Segregación ~\nSeguridad', 'Segregación ~\nReputación',
                                         'Vitalidad ~\nReputación', 'Vitalidad ~\nSatisfacción')), 
           y = estimate, 
           shape = factor(class, levels = c('Alto', 'Medio alto', 'Medio Bajo', 'Bajo')))) +
  geom_hline(yintercept = 0, color = 'red') +
  geom_point(position = position_dodge(width = -0.6), size = 3) +
  geom_linerange(aes(ymin = conf.low, ymax = conf.high),
                 position = position_dodge(width = -0.6), 
                 size = .8) +
  coord_flip() +
  facet_wrap(.~ var) +
  theme(axis.text = element_text(size =  10),
        axis.title = element_text(size = 10, face = "bold")) +
  labs(title = "",
       x = "",
       y = "Coeficientes estandarizados",
       shape = "GSE") +
  scale_x_discrete(limits = rev) 

coef_plot_gse

ggsave(coef_plot_gse,filename = "../3_output/graficos/coef_plot_gse.png", width = 10, height = 7)
```

```{r save-models}
save(fit_msem_apbi, fit_sem_apbi_low, fit_sem_apbi_midlow, fit_sem_apbi_midhigh, fit_sem_apbi_high,
     fit_msem_soci, fit_sem_soci_low, fit_sem_soci_midlow, fit_sem_soci_midhigh, fit_sem_soci_high,
     file = "../3_output/modelos/sem_models.RData")
```
