---
title: "Código de Análisis de Datos"
author: "Cristóbal Ortiz"
date: "08-10-2021"
output: html_document
---

```{r load-library}
library(tidyverse)
library(sjPlot)
```


```{r load-dataset}
getwd()
remove(list = ls())
load("../1_input/data/procesada/elsoc_entorno.RData")
```

```{r comunas-dataset}
#Promedio por comuna
apbi_comuna <-  elsoc_entorno %>%  
  group_by(comuna = comuna.x) %>% 
  summarise(media = mean(apbi, na.rm = T),
            sd = sd(apbi, na.rm = T),
            n = n(),
            esco = mean(nived_com, na.rm = T))

```

```{r boxplot-comuna}
boxplot_apbi <- 
  elsoc_entorno %>% 
  drop_na() %>% 
  ggplot(aes(x = reorder(comuna.x, nived_com), y = apbi)) +
  geom_boxplot() +
  coord_flip() +
  theme(axis.text=element_text(size =  14),
        axis.title=element_text(size = 16, face="bold")) + 
  labs(x=" ", y = "Promedio de apego barrial por comuna")


boxplot_apbi

ggsave(boxplot_apbi, filename= "../3_output/graficos/cap2/boxplot_apbi.png", width = 10, height = 6)
```

```{r Scatter SPB y Reputación por comuna}

comuna_scat <- elsoc_entorno %>% 
  group_by(comuna.x) %>% 
  select(apbi, soci, viol_zon, accs_zon, dens_zon) %>% 
  summarise_all(mean, na.rm = T)

scat_apbi_soci <- 
  plot_scatter(comuna_scat,soci,apbi,
            dot.labels = to_label(comuna_scat$comuna.x),
            fit.line = "lm",
            show.ci = TRUE,
            title = "Gráfico de dispersión para los promedios apego y sociabilidad barrial agrupados por comuna",
            axis.titles = c("Promedio de sociabilidad barrial por comuna","Promedio de apego barrial por comuna"))

ggsave(scat_apbi_soci,filename= "../3_output/graficos/cap2/scat_apbi_soci.png")

scat_apbi_soci
```




```{r Scatter SPB y Nivel de Densidad Poblacional}
scat_apbi_dens <- 
  plot_scatter(comuna_scat, dens_zon, apbi,
            dot.labels = to_label(comuna_scat$comuna.x),
            fit.line = "lm",
            show.ci = TRUE,
            title = "Gráfico de dispersión para los promedios de apego al barrio y densidad zonal agrupados por Comuna",
            axis.titles = c("Promedio de densidad poblacional por comuna","Promedio de apego barrial por comuna"))

ggsave(scat_apbi_dens,filename= "../3_output/graficos/cap2/scat_apbi_dens.png")

scat_apbi_dens
```