---
title: "Código de Análisis de Datos"
author: "Cristóbal Ortiz"
date: "08-10-2021"
output: html_document
---
```{r Ajustes de Markdown,include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = TRUE)
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
options(knitr.kable.NA = '')
```

```{r load-paquetes, include=FALSE}
library(tidyverse)
library(broom)
library(MuMIn) 
library(lme4)
```

```{r load-ds-proc, include=FALSE}
remove(list = ls())
load("../1_input/data/procesada/elsoc.RData")
glimpse(elsoc)
```

```{r apbi-histograma}
elsoc %>% 
  drop_na() %>% 
  ggplot(aes(x = apbi)) +
  geom_histogram(binwidth = 0.5) +
  geom_freqpoly(binwidth = 0.5) + 
  theme_classic()
```

```{r apbi-repb-boxplot}
elsoc %>% 
  drop_na() %>% 
  ggplot(aes(x = repb, y = apbi)) +
  geom_boxplot()
  
```
```{r}
elsoc %>% 
  drop_na() %>% 
  ggplot(aes(x = soci, y = apbi)) +
  geom_point() +
  geom_smooth()
```

```{r parallel-slopes-model}
# Modelling
mod1 <- lm(apbi ~ soci + repb, data = elsoc)
augmented_mod <- 
  lm(apbi ~ soci + repb, data = elsoc) %>% 
  augment() #entrega valores ajustados del modelo .fitted para numérica y factor.var para categórica

# scatterplot, with color
ggplot(augmented_mod, aes(x = soci, y = apbi, color = repb)) + 
  geom_point() + 
  geom_line(aes(y = .fitted))
```

```{r random-slope-model}
elsoc %>% 
  drop_na() %>% 
  ggplot(aes(x = soci, y = apbi, color = repb)) +
  geom_point() +
  geom_smooth(method = "lm", se = 0)

#cambia la pendiente según la reputación barrial 
#esto indica que la sociabilidad y la reputación pueden interactuar en su relación con el apego
#Matemáticamente estos sería equivalente a:
mod3 <- lm(apbi ~ soci + repb + soci:repb, data = elsoc)
#también a:
mod3.1 <- lm(apbi ~ soci*repb, data = elsoc)
summary(mod3)
# En estricto rigor, interacción significa que la relación entre apego y sociabilidad está *moderada* (o se diferencia) por la reputación barrial.
# En este caso podríamos decir que soci:repbPositiva=-0.3 significa que para quienes perciben reputación positiva, por cada unidad que aumente la sociabilidad, el apego disminuye en 0.3 con respecto a quienes perciben reputación negativa. 
```
```{r comparativa-modelos}
mod2 <- lm(apbi ~ soci + soci:repb, data = elsoc)
select <- MuMIn::model.sel(list(mod1, mod2, mod3))
View(select) #nos quedamos con el mod3

#normalidad de residuos mod3
augmented_mod3 <- augment(mod3)
hist(augmented_mod3$.resid) 

#varianza constante mod 3
ggplot(augmented_mod3, aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, 
    lty = 2, color = "red")
```


```{r Promedio de SPB x Comuna, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
bar_sp <- 
  ggplot(elsoc, aes(reorder(sjmisc::to_label(comuna), -apbi),apbi)) +
  geom_bar(stat = "summary") + 
  coord_flip() +
  theme(axis.text=element_text(size=5),
        axis.title=element_text(size=10,face="bold")) + 
  labs(x="Comuna", y="Promedio de Sentido de Pertenencia al Barrio por Comuna")

#ggsave(barras_spb,filename= "../3_output/graficos/barras_spb.pdf")

bar_sp
```

```{r Boxplot SPB x Comuna, echo=FALSE}
box_spb <- 
  ggplot(elsoc, aes(reorder(sjmisc::to_label(comuna), -apbi),apbi)) +
  geom_boxplot() +  
  coord_flip() + 
  theme(axis.text=element_text(size=5),
        axis.title=element_text(size=10,face="bold")) + 
  labs(x="Comuna", y="Promedio de Sentido de Pertenencia al Barrio por Comuna")

#ggsave(boxplot_spb,filename= "../3_output/graficos/boxplot_spb.pdf")

box_spb

```

```{r}
sessionInfo()
```
