---
title: "Código de Análisis de Datos"
output: html_document
---

```{r ajuste-markdown,include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = TRUE)
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
options(knitr.kable.NA = '')
```

```{r cargar-paquetes, include=FALSE}
library(tidyverse)
library(broom)
library(texreg)
library(stargazer)
library(MuMIn)
library(caret)
library(corrplot)
library(sjPlot)
library(sjlabelled)
library(psych)
library(vtable)
library(kableExtra)
```

```{r load-dataset-proc, include=FALSE}
rm(list=ls())
load("../1_input/data/procesada/elsoc.RData")
#View(elsoc)
```

```{r descriptivos-var}
# vector Cronbach
alfa_apbi <- alpha(dplyr::select(elsoc_gs, t02_01, t02_02, t02_03, t02_04)) 
alfa_soci <- alpha(dplyr::select(elsoc_gs, t03_01, t03_02, t03_03, t03_04))
alfa_cfli <- alpha(dplyr::select(elsoc_gs, t11_01, t11_02, t11_03, t11_04))
alfa_acci <- alpha(dplyr::select(elsoc_gs, t06_02, t06_05, t06_06, t06_07))
alfa_geni <- alpha(dplyr::select(elsoc_gs, t04_02, t04_03, t04_04))
alfa_desi <- alpha(dplyr::select(elsoc_gs, t04_06, t04_07))
alfa_cron <- c(alfa_apbi[[1]][,1], alfa_soci[[1]][,1], rep("", 5), alfa_cfli[[1]][,1], 
               alfa_acci[[1]][,1], alfa_geni[[1]][,1], alfa_desi[[1]][,1], rep("", 25)) %>% 
  as.numeric() %>% 
  round(digits = 2)

# tabla descriptivos
desc_table <- sumtable(elsoc %>% select(apbi:time, -apbr), digits = 2, out = "return", labels = TRUE,
                       summ = c('notNA(x)','mean(x)','sd(x)','min(x)','max(x)'),
                       summ.names = c('N Válidos','Media/Porcentaje','SD','Mínimo','Máximo')) %>% 
  mutate("Cronbach" = alfa_cron) #agregamos vector cronbach

desc_table$Cronbach[is.na(desc_table$Cronbach)] <- '' #convertimos los NA en espacios vacíos

write.csv2(desc_table, file = "../3_output/tablas/cap1/1_desc_table.csv") #guardamos
```

```{r correlacion-var}
tab_corr(elsoc %>% select(apbi:time) %>% select_if(is.numeric),
         triangle = "lower", digits = 2, file = "../3_output/tablas/cap1/2_corr_table.doc")
```

```{r ajuste-modelos}
options(na.action = "na.omit")

#modelo con factores sociodemográficos
mod1 <- lm(apbi ~ sexo + edad + educ + essu + regi + time , data = elsoc)
#modelo con factores sociodemográficos + sociales
mod2 <- lm(apbi ~ sexo + edad + educ + essu + regi + time + soci + cnfi + segu + cfli, data = elsoc)
#modelo con  factores sociodemográficos + sociales + físicos
mod3 <- lm(apbi ~ sexo + edad + educ + essu + regi + time + soci + cnfi + segu + cfli + acci + geni, data = elsoc)
#modelo con  factores sociodemográficos + sociales + físicos + simbólicos
mod4 <- lm(apbi ~ sexo + edad + educ + essu + regi + time + soci + cnfi + segu + cfli + acci + geni + repb + desi, data = elsoc)

#comparativa modelos con MuMIn
models <- model.sel(list(mod1,mod2,mod3,mod4))
#View(models)

#screenreg(list(mod1,mod2,mod3,mod4))
```

```{r tabla-modelos}
htmlreg(list(mod1,mod2,mod3,mod4), file = "../3_output/tablas/cap1/3_all_model.doc",
    custom.model.names = c("Modelo 1","Modelo 2","Modelo 3", "Modelo 4"), #nombres modelos
    custom.coef.names = c("Intercepto","Mujer","30 a 49 años","50 a 64 años",">65 años", #sexo y edad
                          "Media","Técnica","Universitaria", "Clase Media","Clase Alta", #clase social
                          "No propietario", "Tiempo de residencia", #régimen viv y tiempo residencia
                          "Sociabilidad barrial","Confianza en Vecinos","Media","Alta","Molestias vecinales", #dim social
                          "Accesibilidad barrial","Encarecimiento barrial", #dim física
                          "Neutra","Positiva","Deseabilidad social"), #dim simbólica
    digits=2)
```

```{r modelos-globales}
elsoc_glob <- elsoc %>% 
    select(-idencuesta, -comuna, -comuna_cod, -apbr) %>% 
    drop_na()
modg <- lm(apbi ~ sexo + edad + educ + essu + regi + time + soci + cnfi + segu + cfli + acci + geni + repb + desi, 
           data = elsoc_glob) #modelo general sin NA

# iteramos modelos rankeados
options(na.action = "na.fail")
#sel_model <- dredge(modg, m.lim = c(0, 15)) #itera combinaciones de modelos y rankea x AICc (demora 2 min aprox)
subsel_model <- subset(sel_model, delta <= 2) #nos deja los mejores modelos (en este caso son 5)

# seleccionamos mejor modelo
bestmodel <- get.models(sel_model, 1)[[1]] #extrae el mejor modelo
#screenreg(bestmodel)
#es lo mismo que:
options(na.action = "na.omit")
mod5 <- lm(apbi ~ time + soci + cnfi + segu + acci + geni + repb + desi, data = elsoc)
#screenreg(mod5)
```

```{r tabla-modelos-glob}
subsel_model <- subsel_model %>% 
  rename(c("Intercepto" = "(Intercept)", "Tiempo de residencia" = "time" , 
           "Sociabilidad barrial" = "soci", "Confianza en Vecinos" = "cnfi",
           "Seguridad barrial" = "segu", "Accesibilidad barrial" = "acci", 
           "Encarecimiento barrial" = "geni", "Reputación barrial" = "repb", 
           "Deseabilidad social" = "desi", "Molestias vecinales" = "cfli",
           "Tramo etario" = "edad", "Nivel educacional" = "educ", 
           "Estatus social subjetivo" = "essu", "Régimen de propiedad vivienda" = "regi",
           "Sexo/Género" = "sexo"))

write.csv2(subsel_model, file = "../3_output/tablas/cap1/4_aicc_table.csv")
```

```{r tabla-pars-model}
htmlreg(list(mod5), file = "../3_output/tablas/cap1/5_pars_model.doc",
    custom.model.names = c("Modelo Parsimonioso"), #nombre modelo
    custom.coef.names = c("Intercepto","Tiempo de residencia", # tiempo residencia
                          "Sociabilidad barrial","Confianza en Vecinos","Media","Alta", #dim social
                          "Accesibilidad barrial","Encarecimiento barrial", #dim física
                          "Neutra","Positiva","Deseabilidad social"), #dim simbólica
    digits=2)
```

```{r plot-coeficientes}
coef_mod5 <-
  tidy(mod5, conf.int = TRUE) %>%  #extraemos parámetros estimados y su intervalo de confianza
    ggplot(aes(x = factor(term, level = c('(Intercept)','desi','repbPositiva','repbNeutra','geni',
                                          'acci','seguMedia','seguAlta','cnfi','soci','time')),
               y = estimate, ymin = conf.low, ymax = conf.high)) +
    scale_x_discrete(labels=c("(Intercept)" = "Intercepto","time" = "Tiempo de residencia", 
                              "soci" = "Sociabilidad barrial", "cnfi" = "Confianza en Vecinos",
                              "seguMedia" = "Seguridad barrial\n(Media)", 
                              "seguAlta" = "Seguridad barrial\n(Alta)", 
                              "acci" = "Accesibilidad barrial",
                              "geni" = "Encarecimiento barrial", "repbNeutra" = "Reputación barrial\n(Neutra)", 
                              "repbPositiva" = "Reputación barrial\n(Positiva)","desi" = "Deseabilidad social")) +
    geom_hline(yintercept = 0, color = 'red' ) + 
    geom_linerange() + 
    geom_point() + 
    ylab(label = "Tamaño de efecto sobre el apego barrial") +
    xlab(label = NULL) +
    coord_flip() +
    theme(axis.text=element_text(size =  12),
          axis.title=element_text(size = 12, face = "bold"))
coef_mod5
save_plot(filename = "../3_output/graficos/cap1/coef_plot.png",fig = coef_mod5, width = 16, height = 10)
```

```{r linealidad}
library(Hmisc)
library(polycor)

plot(mod5, 1)

cor.test(elsoc$apbi, elsoc$time)[[3]] #relación lineal (rechaza H0)
cor.test(elsoc$apbi, elsoc$soci)[[3]] #relación lineal (rechaza H0)
cor.test(elsoc$apbi, elsoc$cnfi)[[3]] #relación lineal (rechaza H0)
hetcor(elsoc$apbi, elsoc$segu) #relación lineal (rechaza H0)
cor.test(elsoc$apbi, elsoc$acci)[[3]] #relación lineal (rechaza H0)
cor.test(elsoc$apbi, elsoc$geni)[[3]] #relación lineal (rechaza H0)
hetcor(elsoc$apbi, elsoc$repb) #relación lineal (rechaza H0)
cor.test(elsoc$apbi, elsoc$desi)[[3]] #relación lineal (rechaza H0)

#SE CUMPLE

```

```{r norm-resid}
plot(mod5, 2)

shapiro.test(mod5$residuals)

#SE CUMPLE
```

```{r homocedasticidad}
plot(mod5, 3)
car::ncvTest(mod5)
lmtest::bptest(mod5)
#NO SE CUMPLE

plot(mod4, 3)
lmtest::bptest(mod4)
```

```{r multicolinealidad}
car::vif(mod5)
#SE CUMPLE
```

```{r casos-influyentes}
plot(mod5, 4)
plot(mod5, 5)

elsoc_sub <- elsoc %>% drop_na()
elsoc_sub$cook <- cooks.distance(mod5)
which(elsoc_sub$cook > 1)

#SE CUMPLE
```

```{r info-sesion}
#sessionInfo()
```

