---
title: "Código preparación"
author: "Cristóbal Ortiz"
date: "08-10-2021"
output: html_document
---
```{r ajustes-markdown,include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = TRUE)
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
options(knitr.kable.NA = '')
```

```{r load-library}
library(tidyverse)
library(psych) #alpha
library(sjmisc) #frq
library(sjlabelled) #etiquetas
```

```{r load-dataset}
remove(list = ls())
load("../1_input/data/original/elsoc-w01-dv/ELSOC_W01_V4.01_R.RData") #base de datos ola 1
```

```{r limpieza-dataset}
elsoc_gs <- elsoc_2016 %>% 
  filter(estrato == 1) %>% 
  dplyr::select(idencuesta, estrato, comuna, comuna_cod, #ids
                t01:t11_04, #variables territoriales
                m0_sexo, m0_edad, m01, d01_01, m33, m34_03, c12_01, m29, m30, nhogar1) #sociodemográficas

elsoc_gs[elsoc_gs == -888 | elsoc_gs == -999] <- NA
```

```{r manipulacion-variables}
elsoc_gs <- elsoc_gs %>% 
  remove_all_labels() %>% 
         #-----Recode Y: Apego al barrio
  mutate(apbi = (t02_01 + t02_02 + t02_03 + t02_04)/4) %>% 
  mutate(apbr = factor(case_when(apbi < 2 ~ 1, apbi < 3 ~ 2,
                                 apbi < 4 ~ 3, apbi <= 5 ~ 4),
                           labels = c('Muy Bajo', 'Bajo', 'Medio', 'Alto')),
         #-----Recode Xi: Experiencia de habitar el barrio
         soci = (t03_01 + t03_02 + t03_03 + t03_04)/4,
         cnfi = t01,
         segu = factor(car::recode(t10, "1:2=1;3=2;4:5=3"),
                           labels = c("Baja",
                                      "Media",
                                      "Alta")),
         cfli = (t11_01 + t11_02 + t11_03 + t11_04)/4,
         acci = (t06_02 + t06_05 + t06_06 + t06_07)/4,
         geni = (t04_02 + t04_03 + t04_04)/3,
         desi = (car::recode(t04_06, "1=5;2=4;3=3;4=2;5=1") 
                 + car::recode(t04_07, "1=5;2=4;3=3;4=2;5=1"))/2,
         repb = factor(car::recode(t08, "1:2=1;3=2;4:5=3"),
                             labels = c("Negativa",
                                        "Neutra", 
                                        "Positiva")),
         #-----Recode Controles: Variables socio-demográficas
         sexo = factor(m0_sexo, labels = c('Hombre', 'Mujer')),
         edad = factor(car::recode(m0_edad, "18:29=1; 30:49=2; 50:64=3; 65:150=4"),
                       labels = c('18-29', '30-49', '50-64', '65 o más')),
         educ = factor(car::recode(m01,"1:3=1; 4:5=2; 6:7=3; 8:10=4"),
                       labels = c("Básica", "Media", "Técnica", "Universitaria")),
         essu = factor(car::recode(d01_01, "c(0,1,2,3)=1; c(4,5)=2; c(6,7,8,9,10)=3"),
                      labels = c("Baja", "Media", "Alta")),
         regi = factor(car::recode(m33, "1:2=0;3:7=1"),
                           labels = c('Propietario','No propietario')),
         time = m34_03) %>% 
         #-----Etiqueta variables
  var_labels(apbi = "Apego Barrial",
             apbr = "Apego Barrial",
             soci = "Sociabilidad barrial",
             cnfi = "Confianza en vecinos",
             segu = 'Seguridad barrial',
             cfli = 'Molestias vecinales',
             acci = 'Accesibilidad barrial',
             geni = 'Encarecimiento barrial',
             desi = 'Deseabilidad social',
             repb = 'Reputación barrial',
             sexo = 'Sexo/Género',
             edad = 'Tramo etario',
             educ = 'Nivel educacional',
             essu = 'Estatus social subjetivo',
             regi = 'Régimen de propiedad vivienda',
             time = 'Tiempo de residencia') 

elsoc_gs$time[elsoc_gs$time == 80] <- 75 #imputamos valor sospechoso 
elsoc_gs$time[elsoc_gs$time == 0] <- 1 #imputamos valor para redondear
```

```{r save-dataset}
elsoc <- elsoc_gs %>%
  select(idencuesta, comuna, comuna_cod, 
         apbi, apbr, soci, cnfi, segu, cfli, acci, geni, desi, repb, 
         sexo, edad, educ, essu, regi, time)

save(elsoc, elsoc_gs, file = "../1_input/data/procesada/elsoc.RData")
```

```{r info-sesion}
sessionInfo()
```

